### ISSUE TITLE
Container fails to establish a connection on MicroOS

### ISSUE THREAD

**Issue by dcermak** [thkukuk/wireguard-container#2]
I tried the container in server mode on a Raspberry Pi running MicroOS as follows:
```shell
podman run -d --rm \
    --cap-add net_admin --cap-add net_raw \
    -e SERVER_IP=192.168.1.50 -p 51820:51820/udp \
    -v /srv/wireguard:/etc/wireguard:Z \
    --name wireguard registry.opensuse.org/home/kukuk/container/container/opensuse/wireguard
```
The container launches, but no connection is established:
```ShellSession
localhost:~ # podman logs wireguard
Starting setup...
* Interface is set to eth0
* NAT disabled
Start wireguard interface (/etc/wireguard/wg0.conf)
[#] ip link add wg0 type wireguard
ip: RTNETLINK answers: Operation not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
ip: can't find device 'wg0'
* Add peer boreas
Unable to modify interface: Protocol not supported
Setting up watches.
Watches established.
```

I have tried to manually execute `ip link add wg0 type wireguard` before launching the container, which does the trick for the container itself. The `wg0` interface is however only usable from inside the container, which is expected, but imho not too useful for a server.

**Comment by dcermak** [comment]
The container appears to work in server mode, but only if you created the `wg0` interface once beforehand **and** start it with `--net=host`. But `--net=host` does not appear to be sufficient to create the `wg0` interface by itself, the process still fails with:
```
[#] ip link add wg0 type wireguard
ip: RTNETLINK answers: Operation not supported
```

**Comment by thkukuk** [comment]
Don't have a Rasperry Pi to play with currently, all in use for something else. 
But with Tumbleweed and openSUSE MicroOS on x86-64 it just worked for me, never saw this error.
Does --privileged instead of the --cap-add option help?
Does it help to load the wireguard module upfront?

**Comment by thkukuk** [comment]
Tried it again: removed the wireguard kernel module, run the container as documented. Kernel module will be loaded, interface will be created.
Maybe SELinux is blocking something for you? Haven't that tested yet.

**Comment by dcermak** [comment]
> Does --privileged instead of the --cap-add option help?

Yes, then the kernel module is loaded.

> Does it help to load the wireguard module upfront?

Yes, that does help as well.



> Maybe SELinux is blocking something for you? Haven't that tested yet.

Yes, SELinux is blocking the loading of kernel modules (see https://medium.com/cri-o/cri-o-has-builtin-selinux-support-6ff45b707cf0) as can be seen in the audit.log:
```
type=AVC msg=audit(1661156301.531:260): avc:  denied  { module_request } for  pid=2779 comm="ip" kmod="netdev-wg0" scontext=system_u:system_r:container_t:s0:c55,c360 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
type=AVC msg=audit(1661156301.531:261): avc:  denied  { module_request } for  pid=2780 comm="ip" kmod="rtnl-link-wireguard" scontext=system_u:system_r:container_t:s0:c55,c360 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
type=AVC msg=audit(1661156301.541:262): avc:  denied  { module_request } for  pid=2782 comm="wg" kmod="net-pf-16-proto-16-family-wireguard" scontext=system_u:system_r:container_t:s0:c55,c360 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
type=AVC msg=audit(1661156301.551:263): avc:  denied  { module_request } for  pid=2783 comm="ip" kmod="netdev-wg0" scontext=system_u:system_r:container_t:s0:c55,c360 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
type=AVC msg=audit(1661156301.571:264): avc:  denied  { module_request } for  pid=2789 comm="wg" kmod="net-pf-16-proto-16-family-wireguard" scontext=system_u:system_r:container_t:s0:c55,c360 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
```

If I understand [`container-selinux/container.te`](https://github.com/containers/container-selinux/blob/bca5876c01c4ba6de0443241b64136e95f6b7355/container.te#L390) correctly, that's the "culprit" here:
```
allow container_runtime_domain self:capability ~{ sys_module };
allow container_runtime_domain self:capability2 ~{ mac_override mac_admin };
allow container_runtime_domain self:cap_userns ~{ sys_module };
allow container_runtime_domain self:cap2_userns ~{ mac_override mac_admin };
```

**Comment by thkukuk** [comment]
> > Does --privileged instead of the --cap-add option help?
> 
> Yes, then the kernel module is loaded.

Ok, then I guess adding additional "--cap-add sys_module" should solve it. Else we need to try all capabilities one by one which get's enabled by --privileged...
Sorry, still didn't managed to setup a test machine yet...

**Comment by thkukuk** [comment]
The following command:
`echo wireguard > /etc/modules-load.d/wireguard.conf`
will load the kernel module at every boot and the wireguard container will work even on SELinux enabeld systems without additional privileges.
I adjusted the documentation accordingly.
