### ISSUE TITLE
[Proposal] Convert this to a BCI image?

### ISSUE THREAD

**Issue by dcermak** [thkukuk/wireguard-container#3]
The wireguard container is very useful and I think it would be very nice to have it as part of the "official" openSUSE images, which are being transitioned to be based on the BCI project.

Would you be interested in moving this container into the BCI project?

**Comment by thkukuk** [comment]
If somebody wants this as container in the BCI project I'm fine if this person creates such a container, but I don't have the time to do and maintain that.
