### ISSUE TITLE
[Proposal] Add `INTERFACE` env var to documentation

### ISSUE THREAD

**Issue by SchoolGuy** [thkukuk/wireguard-container#4]
At the moment the `start` script utilizes the environment variable `INTERFACE`. Its meaning and usage are not documented.

Variable definition:

https://github.com/thkukuk/wireguard-container/blob/4ac8f3c1703c7cefdc81b0e5e3a61a0aaeea0616/usr/local/bin/start#L87

If desired I volunteer to open a PR to add the documentation to the `README.md` file.

**Comment by thkukuk** [comment]
Added
